updating instruction for the gitignore
learn-co-curriculum/dsc-project-template pull request #24
Opened 2022-06-06 16:20 UTC by jilliankim

2022-06-06 18:33 UTC, hoffm386 requested changes
I have a couple of specific requested changes in the README, and also it looks like this is still using the old data

Right now the structure is like this:

```
└──  data
   └── zippedData
       ├── bom.movie_gross.csv.gz
       ├── imdb.name.basics.csv.gz
       ├── imdb.title.akas.csv.gz
       ├── imdb.title.basics.csv.gz
       ├── imdb.title.crew.csv.gz
       ├── imdb.title.principals.csv.gz
       ├── imdb.title.ratings.csv.gz
       ├── rt.movie_info.tsv.gz
       ├── rt.reviews.tsv.gz
       ├── tmdb.movies.csv.gz
       └── tn.movie_budgets.csv.gz
```

Instead it should be like this (matching the [project description](https://github.com/learn-co-curriculum/dsc-phase-1-project-v2-4/)):

```
└── zippedData
    ├── bom.movie_gross.csv.gz
    ├── im.db.zip
    ├── rt.movie_info.tsv.gz
    ├── rt.reviews.tsv.gz
    ├── tmdb.movies.csv.gz
    └── tn.movie_budgets.csv.gz
```

2022-06-06 18:33 UTC, hoffm386 commented on README.md
> +   - Add `*.csv`,`*.tsv`, and `*.db` to the .gitignore file
Could you edit this to say:

> Add `*.csv`,`*.tsv`, and `*.db` to the .gitignore file if you're not sure which specific files to ignore

I think there might be some students who want to include certain (smaller) cleaned data files, which is fine. But this is a good hint for students who are uncertain about where to start

2022-06-06 18:33 UTC, hoffm386 commented on README.md
>     - This README file: `README.md`
Please remove the line

> - This README file: `README.md`

Above it says "Rename the template readme you've been working in by running `git mv TEMPLATE_README.md README.md`" so they should NOT delete `README.md`

2022-06-07 16:15 UTC, jilliankim commented on README.md
> +   - Add `*.csv`,`*.tsv`, and `*.db` to the .gitignore file
I feel like this would go back and add the confusion - if we do want to say that, then we are assuming the students do know of the data limit in github which defeats the purpose of editing this curriculum

2022-06-08 17:12 UTC, hoffm386 commented on README.md
> +   - Add `*.csv`,`*.tsv`, and `*.db` to the .gitignore file
There was a lesson about gitignore so I think students should already be aware of the general idea that some files are too big

The question is whether we want to **tell** them what to do vs. **suggest** one approach that will work, in a context where there are multiple viable options. I tend to prefer the "suggest" approach but if you prefer the "tell" approach we can keep that

2022-06-08 17:16 UTC, hoffm386 requested changes
Just noticed there are a couple places that still say `data` instead of `zippedData` but otherwise this looks good!

2022-06-08 17:16 UTC, hoffm386 commented on README.md
>     - Any unused data files in the `data` folder
Can we change `data` to `zippedData`?

2022-06-08 17:16 UTC, hoffm386 commented on README.md
> +- Utilize the .gitignore file to ignore large unzipped data files in the `data` folder
`data` to `zippedData` here also

2022-06-08 18:01 UTC, hoffm386 approved these changes

2022-06-09 18:51 UTC, merged